---
- name: include os-specific variables
  include_vars: "{{ ansible_os_family }}.yml"

- name: configure mongodb extension
  template: src=mongo.ini.j2 dest={{php_extension_ini_dir}}/{{php_mongo_ini_filename}}.ini

- include: "debian/main.yml"
  when: ansible_os_family == 'Debian'

- include: "redhat/main.yml"
  when: ansible_os_family == 'RedHat'
